File1=open('output.txt','w')
a=input('Enter text to write to the file: ')
writingfile=File1.write(a+'\n')
print('Data successfully written to output.txt.')
File1.close()
File1=open('output.txt','a')
b=input('Enter additional text to append: ')
writingfile=File1.write(b)
print('Data successfully appended.')
File1.close()
File1=open('output.txt','r')
print('Final content of output.txt.: ')
readingfile=File1.read()
print(readingfile)